#! /bin/sh

# Change resolution
#xrandr --output Virtual-1 --mode 1680x1050
#xrandr --output Virtual-1 --mode 2560x1080


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Mount shared folders
#vmhgs-fuse /mnt/hgfs fuse defaults,allow_other 0 0

# Wallpaper
feh --bg-fill /home/g2jz/Pictures/wallpaper.jpg

# Launch Polybar
~/.config/polybar/./launch.sh

# Fix Burpsuite Resolution
wmname LG3D

# Follow mouse
bspc config focus_follow_pointer true

# Border width
bspc config border_width 0

# Picom
picom --experimental-backends &

# Prevent mouse in X mode
xsetroot -cursor_name left_ptr &

